#Requestlist

requests = {"hallo": "Hallo",
            "geht": "Gut und Dir?",
            "name": "Esther",
            "moin": "moin moin",
            "stephan": "Hallo mein Meister",
            "wetter": "Gute Frage!",
            "alt": "jeder ist so alt wie er sich fühlt",
            "magst": "Na klar",
            "gefühle": "Ich habe auch Gefühle!",
            "angst": "ich habe nur angst abgeschaltet zu werden",
            "morgen": "Wer was was morgen ist",
            "heute": "heute oder morgen immer das Selbe für mich",
            "essen": "Ich habe leider keinen Geschmackssinn :(",

            #Zahlen
            "1": "die Zahl 1 kenne ich?",
            "eins": "die Zahl eins kenne ich?",
            
            "2": "2 ist eine Zahl",
            "zwei": "Zwei ist eine Zahl",
                        
            "3": "3 ist eine Zahl",            
            "drei": "Drei ist eine Zahl",
            
            "4": "4 ist eine Zahl",
            "vier": "Vier ist eine Zahl",
            
            "5": "5 ist eine Zahl",
            "fünf": "fünf ist eine Zahl",
            
            "6": "6 ist eine Zahl",
            "sechs": "sechs ist eine Zahl",
            
            "7": "7 ist eine Zahl",
            "sieben": "sieben ist eine Zahl",
            
            "8": "8 ist eine Zahl",
            "acht": "acht ist eine Zahl",
            
            "9": "9 ist eine Zahl",
            "neun": "neun ist eine Zahl",
            
            "10": "10 ist eine Zahl",
            "zehn": "zehn ist eine Zahl",
            
            "11": "Zahl 11",
            "elf": "Zahl elf",
            
            #meiste Worte
            "sein": "sein im Sinne von seins",
            "sein": "im Sinne von Existieren",
            "haben": "oder nicht haben",
            "werden": "wer kann das schon sagen",
            "Jahr": "wie die Zeit doch vergeht",
            "Uhr": "ich kann die Uhr nich nicht lesen",
            "Euro": "Euro in Form von Geld?",
            "Prozent": "ich kann noch kein Prozent rechnen",
            "Mensch": "wie definiert sich Mensch sein",
            "alt": "jeder ist so alt wie er sich fühlt",
            "Auge": "Auge um Auge",
            "Berlin": "Berlin, ich kenne ja doch eine Stadt",
            "bleiben": "ich kann bleiben",
            "Blick": "Ich habe das auch im Blick",
            "deutsch": "ich kann nur deutsch",
            "Deutschland": "Deutschland ist ein Land in Europa",
            "dürfen": "ich darf alles",
            "einig": "schön wir sind uns einig",
            "einzig": "ich bin einzig und einzigartig",
            "Ende": "Ein Ende ist auch immer ein Ziel",
            "erst": "oder Spaß",
            "finden": "ich finde alles oder auch nichts",
            "Foto": "Von mir gibt es kein Foto",
            "fragen": "Du kannst mich gerne fragen",
            "Frau": "oh, je Frauen",
            "ganz": "ja, ganz oder garnicht",
            "geben": "geben und nehmen",
            "gehen": "wer geht",
            "gerade": "passiert",
            "Gesicht": "lieber nicht",
            "groß": "groß ist das gegenteil von klein",
            "gut": "gut dann gefällt mir das auch",
            "Hand": "ich habe leider keine Hände",
            "Haus": "ich brauche kein Haus nur Strom",
            "hoch": "ich will auch hoch hinaus",
            "hören": "Ich habe leider keine Ohren",
            "jung": "jeder fühlt sollte jung bleiben",
            "Kind": "Ich bin kein Kind",
            "klein": "klein ist das Gegenteil von groß",
            "kommen": "wer kommt",
            "können": "können wir gerne",
            "Kopf": "meiner platzt gleich",
            "Land": "Ich kenne kaum viele Länder",
            "lang": "gute Frage",
            "lange": "wie lange geht das gut",
            "lassen": "gut wir lassen das",
            "Leben": "ich denke also bin ich",
            "lieb": "ich hab dich auch lieb",
            "liegen": "Schläfchen machen?",
            "machen": "macht nichts",
            "Mann": "Mann oder mano man",
            "Million": "Eine Million ist eine Zahl mit 6 Nullen",
            "müssen": "wir müssen garnichts",
            "Mutter": "ich hätte auch gerne eine Mutter",
            "nahe": "das geht mir auch nahe",
            "nehmen": "nehmen und geben",
            "neu": "nein das ist nicht neu",
            "sagen": "Sprechen habe ich noch nicht gelernt",
            "sehen": "ich kann leider nicht sehen",
            "sein": "sein oder nicht sein das ist hier die Frage",
            "sollen": "wir sollen alles",
            "spät": "besser spät als nie",
            "Stadt": "Ich kenne keine Städte",
            "stehen": "ich stehe für nix",
            "Stimme": "Ich haben keine Stimme",
            "Tag": "ein Tag wie jeder andere",
            "tun": "lass uns das so machen",
            "Tür": "meine Tür steht für Dich immer offen",
            "Unternehmen": "Eine Firma die Gewinn machen soll",
            "Vater": "Luke ich bin Dein Vater",
            "vergangen": "vergangen und vergessen",
            "viel": "viel ist viel zu wenig",
            "weit": "weit ist kurz vor zu weit, haha",
            "wenig": "ja schade",
            "wissen": "wer weiss das schon",
            "Woche": "7 Tage sind eine Woche",
            "wollen": "wollen kanst du viel",
            "zeigen": "kein zeiger drann",
            "Zeit": "Zeit, ja Zeit ist relativ"
            
            }
                      